# Generated by Django 2.2.9 on 2020-04-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qwerty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='birthYear',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='deathYear',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='knownForTitles',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='nconst',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='primaryName',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='primaryProfession',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
